name: My first pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on:ubuntu-latest

    steps:
       -name: Get the code
        uses: actions/chcekout@v4

      -name: Say hello
        run: echo "Hello, github actions"

      -name: show files
        run: ls
        
