name: My First Pipeline

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello, GitHub Actions!"

      - name: Show files
        run: ls
